### ISSUE TITLE
management-model objects are not serializable

### ISSUE THREAD

**Issue by rkavanap** [Terracotta-OSS/terracotta-management#12]
The statistics and other objects are not serializable. Since they are a 'shared' management-model across multiple systems. shouldn't they be serializable? 

Actually, the data model in the management-model should be java bean style classes (e.g no arg constructor, getter/setter etc) so that it can be serialized into different forms easily. The Kryo serializer was not able to serialize complex objects such as CounterHistory, even with the objenesis instantiator that allows introspection of objects for frameworks without having no-arg constructors.

**Comment by mathieucarbou** [comment]
- also change the hierarchy so that *History abstract class is separated from AbstractStatistic,
- als make sure that this complex test works:

```
public void testComplex() throws Exception {
  List<Sample<Long>> list = new ArrayList<>();
  Sample<Long> l = new Sample<>(1L, 1L);
  list.add(l);
  CounterHistory stat = new CounterHistory("TestCount", list, NumberUnit.COUNT);
  byte[] buffer = codecUnderTest.encode(stat);

  CounterHistory decodedStat = (CounterHistory)codecUnderTest.decode(buffer);
  Assert.assertEquals(...);
  // [...]
}
```
