### ISSUE TITLE
Better serialization support

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-management#44]
- control serialization
- avoid impacts with serialVerionUid
- performance

**Comment by mathieucarbou** [comment]
@anthonydahanne : FYI

**Comment by anthonydahanne** [comment]
is this issue still valid ?

**Comment by mathieucarbou** [comment]
Yes!

-- Mathieu

**Comment by mathieucarbou** [comment]
Moved to Terracotta-OSS/terracotta-platform#92
