### ISSUE TITLE
Artifact missing in mvnrepository: org.terracotta/management-common-resources-v2

### ISSUE THREAD

**Issue by gnanasundar** [Terracotta-OSS/terracotta-management#52]
Hi,

I'm not sure whether this is the correct forum to report this issue. I'm unable to find the following artifact in mvnrepository.com:

http://mvnrepository.com/artifact/org.terracotta/management-common-resources-v2

This seems to be a required dependency when I include management-ehcache-v2 dependency in my pom.

Any idea? Any suggestion or help will be greatly appreciated.

Thanks,
-Gnana

**Comment by mathieucarbou** [comment]
@anthonydahanne : any idea ?

**Comment by gnanasundar** [comment]
Quick update: I was able to find this jar in the following maven repo:

http://jcenter.bintray.com/

So I added this to our nexus.
